[package]
name = "bocleaner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bounded-integer = { version = "0.5", features = ["types"] }
regex = "1.5"
anyhow = "1.0"
lazy_static = "1.4"
